import chromadb, json
client = chromadb.PersistentClient(path="knowledge_db")
print("컬렉션 목록:", [c.name for c in client.list_collections()])
coll = client.get_collection("tacit_knowledge_full")
print("문서 수:", coll.count())
res = coll.get(limit=1, include=["documents","metadatas","embeddings"])
print("\n--- ids[0] ---")
print(res["ids"][0])
print("\n--- documents[0] (임베딩 대상 텍스트) ---")
print(res["documents"][0])
print("\n--- embeddings[0] 차원수 ---")
print(len(res["embeddings"][0]))
print("\n--- metadatas[0] 키 ---")
print(list(res["metadatas"][0].keys()))
print("\n--- metadatas[0].raw_json (앞 300자) ---")
print(res["metadatas"][0]["raw_json"][:300])
